spring:
  application:
    name: IDENTITY-SERVICE
  cloud:
    config:
      label: main
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USERNAME:user}:${CONFIG_SERVER_USERNAME:sa}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8099}?fail-fast=true&max-attempts=20&max-interval=15000&multiplier=1.8&initial-interval=11000
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:identitydb}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}